repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-ast
      - id: check-yaml
      #- id: check-toml
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: forbid-new-submodules
#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v3.0.0a5 # tag to search in the repo above
    # PLEASE NOTE: pre-commit runs pylint from an isolated virtualenv. 
    # Many of pylint's checks perform dynamic analysis which will fail there.
    # You may find configuring pylint as a local hook more useful.
#    hooks:
#      - id: pylint # name of the test tool/check
     #   -   id: pylint
     #       name: pylint
     #       entry: pylint
     #       language: system
     #       types: [python]
     #       require_serial: true
     #   -   id: check-x
     #       name: Check X
     #       entry: ./bin/check-x.sh
     #       language: script
     #       files: \.x$
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''  # Use the sha / tag you want to point at
    # Note that this approach sets args: [-i],
    # If you are configuring autopep8 using args you'll want to include either -i (--in-place) or -d (--diff). 
    # It is usually better to configure autopep8 in its config file.
    hooks:
      - id: autopep8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [-r, --exit-zero]
        #name: bandit
        #description: 'Bandit is a tool for finding common security issues in Python code'
        #entry: bandit
        #language: python
        #language_version: python3
        #types: [python]
#  - repo: https://github.com/asottile/dead
#    # checks for dead code, see https://github.com/asottile/dead for options
#    rev: v1.5.0
#    hooks:
#      - id: dead
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: shellcheck
#  - repo: git://github.com/jstewmon/check-swagger
#    rev: v0.1.4
#    hooks:
#      - id: check-swagger
  - repo: https://github.com/pre-commit/mirrors-csslint
    rev: ''  # Use the sha / tag you want to point at
    # Please add a .csslintrc file to your project. 
    # See https://github.com/CSSLint/csslint/wiki/Command-line-interface#configuration-files for config details
    # review the need for css-linting from pre-config repo (see above)
    hooks:
      - id: csslint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    # see https://github.com/Lucas-C/pre-commit-hooks for flags on insert-license
    hooks:
      - id: insert-license
        files: \.groovy$
        args:
          - --license-filepath
          - src/license_header.txt        # defaults to: LICENSE.txt
          - --comment-style
          - //                            # defaults to:  #
#  - repo: https://github.com/igorshubovych/markdownlint-cli
#    rev: v0.32.2
#    hooks:
#      - id: markdownlint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_checkov 
 
